version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
    environment:
      - CLEANING_DB_PATH=/app/airbnb_cleaning.db
    restart: unless-stopped

